package com.esgframework.models;

public enum EmissionCategory {
    // Scope 1 Categories
    STATIONARY_COMBUSTION,
    MOBILE_COMBUSTION,
    PROCESS_EMISSIONS,
    FUGITIVE_EMISSIONS,

    // Scope 2 Categories
    PURCHASED_ELECTRICITY,
    PURCHASED_HEATING,
    PURCHASED_COOLING,
    PURCHASED_STEAM,

    // Scope 3 Categories
    PURCHASED_GOODS_SERVICES,
    CAPITAL_GOODS,
    FUEL_ENERGY_ACTIVITIES,
    TRANSPORTATION_DISTRIBUTION,
    WASTE_GENERATED,
    BUSINESS_TRAVEL,
    EMPLOYEE_COMMUTING,
    LEASED_ASSETS,
    INVESTMENTS,
    DOWNSTREAM_TRANSPORTATION,
    PROCESSING_SOLD_PRODUCTS,
    USE_OF_SOLD_PRODUCTS,
    END_OF_LIFE_PRODUCTS,
    FRANCHISES
}
